name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            qt_arch: gcc_64
          - os: windows-latest
            qt_arch: win64_msvc2019_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.2
          arch: ${{ matrix.qt_arch }}

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: cmake -S . -B build -DQt6_DIR="$Qt6_DIR" -DCMAKE_BUILD_TYPE=Release

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DQt6_DIR="$env:Qt6_DIR"

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: cmake --build build --config Release

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: cmake --build build --config Release
